<HTML>
<HEAD>
<meta charset="UTF-8">
<title>TestContext.asyncAssertFailure - vertx</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">vertx</a>&nbsp;/&nbsp;<a href="../index.html">io.vertx.ext.unit</a>&nbsp;/&nbsp;<a href="index.html">TestContext</a>&nbsp;/&nbsp;<a href=".">asyncAssertFailure</a><br/>
<br/>
<h1>asyncAssertFailure</h1>
<a name="io.vertx.ext.unit.TestContext$asyncAssertFailure()"></a>
<code><span class="keyword">abstract</span> <span class="keyword">fun </span><span class="symbol">&lt;</span><span class="identifier">T</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-any/index.html"><span class="identifier">Any</span></a><span class="symbol">&gt;</span> <span class="identifier">asyncAssertFailure</span><span class="symbol">(</span><span class="symbol">)</span><span class="symbol">: </span><span class="identifier">Handler</span><span class="symbol">&lt;</span><span class="identifier">AsyncResult</span><span class="symbol">&lt;</span><span class="identifier">T</span><span class="symbol">&gt;</span><span class="symbol">&gt;</span></code>
<p>Creates and returns a new async handler, the returned handler controls the completion of the test. When the returned handler is called back with a failed result it completes the async operation. When the returned handler is called back with a succeeded result it fails the test.</p>
<p><strong>Return</strong><br/>
the async result handler</p>
<a name="io.vertx.ext.unit.TestContext$asyncAssertFailure(io.vertx.core.Handler((kotlin.Throwable)))"></a>
<code><span class="keyword">abstract</span> <span class="keyword">fun </span><span class="symbol">&lt;</span><span class="identifier">T</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-any/index.html"><span class="identifier">Any</span></a><span class="symbol">&gt;</span> <span class="identifier">asyncAssertFailure</span><span class="symbol">(</span><span class="identifier" id="io.vertx.ext.unit.TestContext$asyncAssertFailure(io.vertx.core.Handler((kotlin.Throwable)))/causeHandler">causeHandler</span><span class="symbol">:</span>&nbsp;<span class="identifier">Handler</span><span class="symbol">&lt;</span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">&gt;</span><span class="symbol">)</span><span class="symbol">: </span><span class="identifier">Handler</span><span class="symbol">&lt;</span><span class="identifier">AsyncResult</span><span class="symbol">&lt;</span><span class="identifier">T</span><span class="symbol">&gt;</span><span class="symbol">&gt;</span></code>
<p>Creates and returns a new async handler, the returned handler controls the completion of the test. When the returned handler is called back with a failed result it completes the async operation. When the returned handler is called back with a succeeded result it fails the test.</p>
<h3>Parameters</h3>
<p><a name="causeHandler"></a>
<code>causeHandler</code> - the cause handler</p>
<p><strong>Return</strong><br/>
the async result handler</p>
</BODY>
</HTML>
